# -*- coding: utf-8 -*-
"""AS_3_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBZ6kMC5bWO8ZJq93QZeNRiuXIF9OaB9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score

data = pd.read_csv("/content/sample_data/customer_segmentation.csv")

print(data.head())

X = data[["Age", "Annual_Income", "Spending_Score"]]

wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

plt.figure()
plt.plot(range(1, 11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

k = 4  # choose based on elbow
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)

labels = kmeans.fit_predict(X)

data["Cluster"] = labels

sil_score = silhouette_score(X, labels)
db_score = davies_bouldin_score(X, labels)

print("\nClustering Evaluation:")
print("Silhouette Score:", sil_score)
print("Davies-Bouldin Score:", db_score)

plt.figure()
plt.scatter(data["Annual_Income"], data["Spending_Score"], c=labels)
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Segments")
plt.show()

print("\nCluster Centers:")
print(kmeans.cluster_centers_)

